// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db_access

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Application struct {
	ID                   pgtype.UUID
	Name                 string
	PassPhrase           string
	ApiKey               string
	AccessTokenDuration  int32
	RefreshTokenDuration int32
}

type User struct {
	ID            pgtype.UUID
	ApplicationID pgtype.UUID
	Username      string
	Pass          string
	LastLogin     pgtype.Timestamp
}
